datas <- read.csv("/home/kristijan/github/FootballEvolcion/Datas/SaveData/save_csv_Expend_BATCH.csv")
print(datas)
x <- data.frame(datas)
print("\n\n\t DATA FRAME")
print(x)
print(nrow(x))
print(ncol(x))
