datas <- read.csv("/home/kristijan/github/FootballEvolcion/Datas/SaveData/save_csv_Expend_BATCH.csv")
print(datas)
x <- data.frame(datas)
colnames(x) <- c("Name of League", "Year of Season","Nationality", "Expend by player","Expend + Inflation by player") 
print("\n\n\t DATA FRAME")
print(x)
print(nrow(x))
print(ncol(x))
print(names(x))
